# Generated by Django 5.0.4 on 2024-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='productos/galeria/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos_seleccionados', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aperitivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aperitivo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_pequenio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_mediano', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_grande', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['aperitivo'], name='menu_aperit_aperiti_f2ca55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_pequenio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_mediano', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_grande', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['bebida'], name='menu_bebida_bebida_49b453_idx')],
            },
        ),
        migrations.CreateModel(
            name='Platillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platillo_nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_pequenio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_mediano', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_grande', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platillo_nombre'], name='menu_platil_platill_c8e69e_idx')],
            },
        ),
    ]
